# SPDX-License-Identifier: GPL-3.0-or-later
# Prepare the locally bundled faces using Common's immutable asset hashes.
get_filename_component(LSM_FONT_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
include("${LSM_FONT_SOURCE_ROOT}/src/infiltratr-common/cmake/InfiltratrTypographyAssets.cmake")
if(NOT DEFINED LSM_FONT_OUTPUT_DIR)
    message(FATAL_ERROR "LSM_FONT_OUTPUT_DIR is required")
endif()
set(LSM_FONT_ARCHIVE "${LSM_FONT_SOURCE_ROOT}/support/resources/fonts/mb-corpo-fonts.tar.xz")
file(SHA256 "${LSM_FONT_ARCHIVE}" LSM_FONT_ARCHIVE_HASH)
if(NOT LSM_FONT_ARCHIVE_HASH STREQUAL INFILTRATR_MB_CORPO_ARCHIVE_SHA256)
    message(FATAL_ERROR "Bundled MB Corpo archive does not match Common's canonical SHA-256")
endif()
file(MAKE_DIRECTORY "${LSM_FONT_OUTPUT_DIR}")
file(ARCHIVE_EXTRACT INPUT "${LSM_FONT_ARCHIVE}" DESTINATION "${LSM_FONT_OUTPUT_DIR}")
foreach(LSM_FONT_ROLE BRAND_REGULAR UI_REGULAR UI_BOLD)
    set(LSM_FONT_FILE "${INFILTRATR_MB_CORPO_${LSM_FONT_ROLE}_FILE}")
    file(SHA256 "${LSM_FONT_OUTPUT_DIR}/${LSM_FONT_FILE}" LSM_FONT_HASH)
    if(NOT LSM_FONT_HASH STREQUAL INFILTRATR_MB_CORPO_${LSM_FONT_ROLE}_SHA256)
        message(FATAL_ERROR "Bundled ${LSM_FONT_FILE} does not match Common's canonical SHA-256")
    endif()
endforeach()
message(STATUS "Verified all three locally bundled MB Corpo faces")
